var content;

content = `<p class="MsoNormal" style="text-indent: -105.15pt; line-height: 111%; margin: 0cm 115.6pt 14.5pt 105.15pt;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 111%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';"><span style="mso-spacerun: yes;">&nbsp;</span></span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 26.0pt; mso-bidi-font-size: 11.0pt; line-height: 111%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">CURRICULUM VITAE </span></strong></p>
<h1>PERSONAL PARTICULARS<span style="text-decoration: none; text-underline: none;"> </span></h1>
<table class="TableGrid" style="width: 175.4pt; border-collapse: collapse; mso-yfti-tbllook: 1184; mso-padding-alt: 0cm 0cm 0cm 0cm;" border="0" width="0" cellspacing="0" cellpadding="0">
<tbody>
<tr style="mso-yfti-irow: 0; mso-yfti-firstrow: yes; height: 17.1pt;">
<td style="width: 108.05pt; padding: 0cm 0cm 0cm 0cm; height: 17.1pt;" valign="top" width="144">
<p class="MsoNormal"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">First Name <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span>: </span></p>
</td>
<td style="width: 67.35pt; padding: 0cm 0cm 0cm 0cm; height: 17.1pt;" valign="top" width="90">
<p class="MsoNormal"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Faith </span></p>
</td>
</tr>
<tr style="mso-yfti-irow: 1; height: 20.75pt;">
<td style="width: 108.05pt; padding: 0cm 0cm 0cm 0cm; height: 20.75pt;" valign="top" width="144">
<p class="MsoNormal"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Middle Name : </span></p>
</td>
<td style="width: 67.35pt; padding: 0cm 0cm 0cm 0cm; height: 20.75pt;" valign="top" width="90">
<p class="MsoNormal"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">A </span></p>
</td>
</tr>
<tr style="mso-yfti-irow: 2; mso-yfti-lastrow: yes; height: 20.2pt;">
<td style="width: 108.05pt; padding: 0cm 0cm 0cm 0cm; height: 20.2pt;" valign="top" width="144">
<p class="MsoNormal"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Last Name <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>: </span></p>
</td>
<td style="width: 67.35pt; padding: 0cm 0cm 0cm 0cm; height: 20.2pt;" valign="top" width="90">
<p class="MsoNormal"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Weledi </span></p>
</td>
</tr>
</tbody>
</table>
<p class="MsoNormal" style="margin-bottom: 4.75pt; line-height: normal;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 9.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';"><span style="mso-spacerun: yes;">&nbsp;</span></span></strong></p>
<h1>CONTACT DETAILS<span style="text-decoration: none; text-underline: none;"> </span></h1>
<h2>Faith A. Weledi,</h2>
<p class="MsoNormal" style="margin-bottom: 6.8pt; line-height: normal;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman'; background: yellow;">P.O Box 53 Kibaha, </span></strong></p>
<h2>Pwani,</h2>
<h2>Mobile: +255 (0) 43 255 946</h2>
<p class="MsoNormal" style="margin-bottom: 7.0pt; line-height: normal;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">E-mail:</span></strong><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Bookman Old Style',serif; mso-fareast-font-family: 'Bookman Old Style'; mso-bidi-font-family: 'Bookman Old Style';"> </span><strong style="mso-bidi-font-weight: normal;"><u style="text-underline: blue;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman'; color: blue;">faithmwaipopo509@gmail.com</span></u></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';"><span style="mso-spacerun: yes;">&nbsp; </span></span></strong></p>
<p class="MsoNormal" style="line-height: normal;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';"><span style="mso-spacerun: yes;">&nbsp;</span></span></strong></p>
<h1>EDUCATION BACKGROUND:<span style="text-decoration: none; text-underline: none;"> </span></h1>
<table class="TableGrid" style="width: 482.1pt; margin-left: .25pt; border-collapse: collapse; mso-yfti-tbllook: 1184; mso-padding-alt: 0cm 2.35pt 0cm 5.3pt;" border="0" width="0" cellspacing="0" cellpadding="0">
<tbody>
<tr style="mso-yfti-irow: 0; mso-yfti-firstrow: yes; height: 14.4pt;">
<td style="width: 32.2pt; border: solid black 1.0pt; mso-border-alt: solid black .5pt; padding: 0cm 2.35pt 0cm 5.3pt; height: 14.4pt;" valign="top" width="43">
<p class="MsoNormal" style="margin-left: .25pt;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">S/N </span></strong></p>
</td>
<td style="width: 158.2pt; border: solid black 1.0pt; border-left: none; mso-border-left-alt: solid black .5pt; mso-border-alt: solid black .5pt; padding: 0cm 2.35pt 0cm 5.3pt; height: 14.4pt;" valign="top" width="211">
<p class="MsoNormal" style="margin-left: .25pt;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">COURSE ATTENDED </span></strong></p>
</td>
<td style="width: 78.0pt; border: solid black 1.0pt; border-left: none; mso-border-left-alt: solid black .5pt; mso-border-alt: solid black .5pt; padding: 0cm 2.35pt 0cm 5.3pt; height: 14.4pt;" valign="top" width="104">
<p class="MsoNormal" style="margin-left: .25pt; text-align: justify; text-justify: inter-ideograph;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">DURATION </span></strong></p>
</td>
<td style="width: 117.15pt; border: solid black 1.0pt; border-left: none; mso-border-left-alt: solid black .5pt; mso-border-alt: solid black .5pt; padding: 0cm 2.35pt 0cm 5.3pt; height: 14.4pt;" valign="top" width="156">
<p class="MsoNormal" style="margin-left: .25pt;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">INSTITUTION </span></strong></p>
</td>
<td style="width: 96.55pt; border: solid black 1.0pt; border-left: none; mso-border-left-alt: solid black .5pt; mso-border-alt: solid black .5pt; padding: 0cm 2.35pt 0cm 5.3pt; height: 14.4pt;" valign="top" width="129">
<p class="MsoNormal"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">AWARD </span></strong></p>
</td>
</tr>
<tr style="mso-yfti-irow: 1; height: 16.3pt;">
<td style="width: 32.2pt; border: solid black 1.0pt; border-top: none; mso-border-top-alt: solid black .5pt; mso-border-alt: solid black .5pt; padding: 0cm 2.35pt 0cm 5.3pt; height: 16.3pt;" valign="top" width="43">
<p class="MsoNormal" style="margin-left: .25pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';"><span style="mso-spacerun: yes;">&nbsp;</span></span></p>
</td>
<td style="width: 158.2pt; border-top: none; border-left: none; border-bottom: solid black 1.0pt; border-right: solid black 1.0pt; mso-border-top-alt: solid black .5pt; mso-border-left-alt: solid black .5pt; mso-border-alt: solid black .5pt; padding: 0cm 2.35pt 0cm 5.3pt; height: 16.3pt;" valign="top" width="211">
<p class="MsoNormal" style="margin-left: .25pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';"><span style="mso-spacerun: yes;">&nbsp;</span></span></p>
</td>
<td style="width: 78.0pt; border-top: none; border-left: none; border-bottom: solid black 1.0pt; border-right: solid black 1.0pt; mso-border-top-alt: solid black .5pt; mso-border-left-alt: solid black .5pt; mso-border-alt: solid black .5pt; padding: 0cm 2.35pt 0cm 5.3pt; height: 16.3pt;" valign="top" width="104">
<p class="MsoNormal" style="margin-left: .25pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';"><span style="mso-spacerun: yes;">&nbsp;</span></span></p>
</td>
<td style="width: 117.15pt; border-top: none; border-left: none; border-bottom: solid black 1.0pt; border-right: solid black 1.0pt; mso-border-top-alt: solid black .5pt; mso-border-left-alt: solid black .5pt; mso-border-alt: solid black .5pt; padding: 0cm 2.35pt 0cm 5.3pt; height: 16.3pt;" valign="top" width="156">
<p class="MsoNormal" style="margin-left: .25pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';"><span style="mso-spacerun: yes;">&nbsp;</span></span></p>
</td>
<td style="width: 96.55pt; border-top: none; border-left: none; border-bottom: solid black 1.0pt; border-right: solid black 1.0pt; mso-border-top-alt: solid black .5pt; mso-border-left-alt: solid black .5pt; mso-border-alt: solid black .5pt; padding: 0cm 2.35pt 0cm 5.3pt; height: 16.3pt;" valign="top" width="129">
<p class="MsoNormal"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';"><span style="mso-spacerun: yes;">&nbsp;</span></span></p>
</td>
</tr>
<tr style="mso-yfti-irow: 2; height: 64.1pt;">
<td style="width: 32.2pt; border: solid black 1.0pt; border-top: none; mso-border-top-alt: solid black .5pt; mso-border-alt: solid black .5pt; padding: 0cm 2.35pt 0cm 5.3pt; height: 64.1pt;" valign="top" width="43">
<p class="MsoNormal" style="margin-left: .25pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">1 </span></p>
</td>
<td style="width: 158.2pt; border-top: none; border-left: none; border-bottom: solid black 1.0pt; border-right: solid black 1.0pt; mso-border-top-alt: solid black .5pt; mso-border-left-alt: solid black .5pt; mso-border-alt: solid black .5pt; padding: 0cm 2.35pt 0cm 5.3pt; height: 64.1pt;" valign="top" width="211">
<p class="MsoNormal" style="margin-left: .25pt; text-align: justify; text-justify: inter-ideograph;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Bachelor of international economics and trade </span></p>
</td>
<td style="width: 78.0pt; border-top: none; border-left: none; border-bottom: solid black 1.0pt; border-right: solid black 1.0pt; mso-border-top-alt: solid black .5pt; mso-border-left-alt: solid black .5pt; mso-border-alt: solid black .5pt; padding: 0cm 2.35pt 0cm 5.3pt; height: 64.1pt;" valign="top" width="104">
<p class="MsoNormal" style="margin-left: .25pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">2017-2021 </span></p>
</td>
<td style="width: 117.15pt; border-top: none; border-left: none; border-bottom: solid black 1.0pt; border-right: solid black 1.0pt; mso-border-top-alt: solid black .5pt; mso-border-left-alt: solid black .5pt; mso-border-alt: solid black .5pt; padding: 0cm 2.35pt 0cm 5.3pt; height: 64.1pt;" valign="top" width="156">
<p class="MsoNormal" style="margin-left: .25pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Majimaji university </span></p>
</td>
<td style="width: 96.55pt; border-top: none; border-left: none; border-bottom: solid black 1.0pt; border-right: solid black 1.0pt; mso-border-top-alt: solid black .5pt; mso-border-left-alt: solid black .5pt; mso-border-alt: solid black .5pt; padding: 0cm 2.35pt 0cm 5.3pt; height: 64.1pt;" valign="top" width="129">
<p class="MsoNormal" style="margin-bottom: 1.95pt; line-height: normal;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Bachelor <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>of </span></p>
<p class="MsoNormal" style="margin-bottom: 2.25pt; line-height: normal;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">international </span></p>
<p class="MsoNormal" style="margin-bottom: 1.95pt; text-align: justify; text-justify: inter-ideograph; line-height: normal;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">economics and </span></p>
<p class="MsoNormal"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">trade </span></p>
</td>
</tr>
<tr style="mso-yfti-irow: 3; height: 95.8pt;">
<td style="width: 32.2pt; border: solid black 1.0pt; border-top: none; mso-border-top-alt: solid black .5pt; mso-border-alt: solid black .5pt; padding: 0cm 2.35pt 0cm 5.3pt; height: 95.8pt;" valign="top" width="43">
<p class="MsoNormal" style="margin-left: .25pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">2 </span></p>
</td>
<td style="width: 158.2pt; border-top: none; border-left: none; border-bottom: solid black 1.0pt; border-right: solid black 1.0pt; mso-border-top-alt: solid black .5pt; mso-border-left-alt: solid black .5pt; mso-border-alt: solid black .5pt; padding: 0cm 2.35pt 0cm 5.3pt; height: 95.8pt;" valign="top" width="211">
<p class="MsoNormal" style="margin-left: .25pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Advanced school education </span></p>
</td>
<td style="width: 78.0pt; border-top: none; border-left: none; border-bottom: solid black 1.0pt; border-right: solid black 1.0pt; mso-border-top-alt: solid black .5pt; mso-border-left-alt: solid black .5pt; mso-border-alt: solid black .5pt; padding: 0cm 2.35pt 0cm 5.3pt; height: 95.8pt;" valign="top" width="104">
<p class="MsoNormal" style="margin-left: .25pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">2014-2016 </span></p>
</td>
<td style="width: 117.15pt; border-top: none; border-left: none; border-bottom: solid black 1.0pt; border-right: solid black 1.0pt; mso-border-top-alt: solid black .5pt; mso-border-left-alt: solid black .5pt; mso-border-alt: solid black .5pt; padding: 0cm 2.35pt 0cm 5.3pt; height: 95.8pt;" valign="top" width="156">
<p class="MsoNormal" style="line-height: normal; margin: 0cm 0cm 1.95pt .25pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Umoja </span></p>
<p class="MsoNormal" style="margin-left: .25pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Secondary School </span></p>
</td>
<td style="width: 96.55pt; border-top: none; border-left: none; border-bottom: solid black 1.0pt; border-right: solid black 1.0pt; mso-border-top-alt: solid black .5pt; mso-border-left-alt: solid black .5pt; mso-border-alt: solid black .5pt; padding: 0cm 2.35pt 0cm 5.3pt; height: 95.8pt;" valign="top" width="129">
<p class="MsoNormal" style="margin-bottom: 1.95pt; line-height: normal;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Advanced </span></p>
<p class="MsoNormal" style="margin-bottom: 1.9pt; line-height: 111%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 111%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Certificate <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>of Secondary </span></p>
<p class="MsoNormal" style="margin-bottom: 2.0pt; line-height: normal;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">School Education </span></p>
<p class="MsoNormal" style="margin-bottom: 1.95pt; line-height: normal;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">(ACSEE) </span></p>
<p class="MsoNormal"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';"><span style="mso-spacerun: yes;">&nbsp;</span></span></p>
</td>
</tr>
<tr style="mso-yfti-irow: 4; mso-yfti-lastrow: yes; height: 63.85pt;">
<td style="width: 32.2pt; border: solid black 1.0pt; border-top: none; mso-border-top-alt: solid black .5pt; mso-border-alt: solid black .5pt; padding: 0cm 2.35pt 0cm 5.3pt; height: 63.85pt;" valign="top" width="43">
<p class="MsoNormal" style="margin-left: .25pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">3 </span></p>
</td>
<td style="width: 158.2pt; border-top: none; border-left: none; border-bottom: solid black 1.0pt; border-right: solid black 1.0pt; mso-border-top-alt: solid black .5pt; mso-border-left-alt: solid black .5pt; mso-border-alt: solid black .5pt; padding: 0cm 2.35pt 0cm 5.3pt; height: 63.85pt;" valign="top" width="211">
<p class="MsoNormal" style="margin-left: .25pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Secondary school education </span></p>
</td>
<td style="width: 78.0pt; border-top: none; border-left: none; border-bottom: solid black 1.0pt; border-right: solid black 1.0pt; mso-border-top-alt: solid black .5pt; mso-border-left-alt: solid black .5pt; mso-border-alt: solid black .5pt; padding: 0cm 2.35pt 0cm 5.3pt; height: 63.85pt;" valign="top" width="104">
<p class="MsoNormal" style="margin-left: .25pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">2010-2013 </span></p>
</td>
<td style="width: 117.15pt; border-top: none; border-left: none; border-bottom: solid black 1.0pt; border-right: solid black 1.0pt; mso-border-top-alt: solid black .5pt; mso-border-left-alt: solid black .5pt; mso-border-alt: solid black .5pt; padding: 0cm 2.35pt 0cm 5.3pt; height: 63.85pt;" valign="top" width="156">
<p class="MsoNormal" style="line-height: normal; margin: 0cm 0cm 1.95pt .25pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Mazoezi</span></p>
<p class="MsoNormal" style="margin-left: .25pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Secondary School </span></p>
</td>
<td style="width: 96.55pt; border-top: none; border-left: none; border-bottom: solid black 1.0pt; border-right: solid black 1.0pt; mso-border-top-alt: solid black .5pt; mso-border-left-alt: solid black .5pt; mso-border-alt: solid black .5pt; padding: 0cm 2.35pt 0cm 5.3pt; height: 63.85pt;" valign="top" width="129">
<p class="MsoNormal" style="margin-bottom: 1.95pt; line-height: normal;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Certificate <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>of </span></p>
<p class="MsoNormal" style="margin-bottom: 1.95pt; line-height: normal;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Secondary </span></p>
<p class="MsoNormal" style="margin-bottom: 2.0pt; line-height: normal;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">School </span></p>
<p class="MsoNormal"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 115%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Education (CSE) </span></p>
</td>
</tr>
</tbody>
</table>
<p class="MsoNormal" style="margin-bottom: 6.5pt; line-height: normal;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 7.05pt; line-height: normal;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';"><span style="mso-spacerun: yes;">&nbsp;</span></span></p>
<h1>WORK EXPERIENCE<span style="text-decoration: none; text-underline: none;"> </span></h1>
<h3><span style="text-decoration: none; text-underline: none;">&nbsp;</span></h3>
<h3><span style="text-decoration: none; text-underline: none;">1</span><span style="font-weight: normal; text-decoration: none; text-underline: none;">.<span style="mso-spacerun: yes;">&nbsp;&nbsp; </span>2020-2021</span> TANZANIA REVENUE AUTHORITY (RUKWA).<span style="text-decoration: none; text-underline: none;"> </span></h3>
<h2 style="margin-left: 108.55pt;">Position: Intern</h2>
<h1 style="margin-left: 108.55pt;">Duties and Responsibilities:<span style="text-decoration: none; text-underline: none;"> </span></h1>
<p class="MsoNormal" style="text-indent: -18.0pt; line-height: normal; mso-list: l2 level1 lfo1; margin: 0cm 0cm 7.75pt 18.0pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">&bull;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Estimation of tax from various customers.<strong style="mso-bidi-font-weight: normal;"> </strong></span></p>
<p class="MsoNormal" style="text-indent: -18.0pt; line-height: normal; mso-list: l2 level1 lfo1; margin: 0cm 0cm 7.35pt 18.0pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">&bull;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Review different documents and looking for its correctness<strong style="mso-bidi-font-weight: normal;"> </strong></span></p>
<p class="MsoNormal" style="text-indent: -18.0pt; line-height: normal; mso-list: l2 level1 lfo1; margin: 0cm 0cm 6.8pt 18.0pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">&bull;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">taking notes on evaluation of different kinds of taxes from customers.<strong style="mso-bidi-font-weight: normal;"> </strong></span></p>
<p class="MsoNormal" style="margin-bottom: 6.5pt; line-height: normal;">&nbsp;</p>
<p class="MsoNormal" style="line-height: normal; margin: 0cm 0cm 7.0pt 144.05pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';"><span style="mso-spacerun: yes;">&nbsp;</span></span></p>
<h1>TRANSFERABLE SKILLS AND ABILITIES<span style="text-decoration: none; text-underline: none;"> </span></h1>
<p class="MsoNormal" style="text-indent: -18.05pt; line-height: normal; mso-list: l0 level1 lfo2; margin: 0cm -.75pt 7.35pt 35.3pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">&bull;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Excellent interpersonal, team work and multi-tasking skills.<strong style="mso-bidi-font-weight: normal;"> </strong></span></p>
<p class="MsoNormal" style="text-indent: -18.05pt; line-height: normal; mso-list: l0 level1 lfo2; margin: 0cm -.75pt 7.35pt 35.3pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">&bull;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Ability to work in a demanding and busy working environment.<strong style="mso-bidi-font-weight: normal;"> </strong></span></p>
<p class="MsoNormal" style="text-indent: -18.05pt; line-height: 145%; mso-list: l0 level1 lfo2; margin: 0cm -.75pt 7.35pt 35.3pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 145%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">&bull;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 145%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Good communication skills with essential insight and diplomacy with others and competent in providing concise and clear instructions when required to do so. </span></p>
<p class="MsoNormal" style="text-indent: -18.05pt; line-height: normal; mso-list: l0 level1 lfo2; margin: 0cm -.75pt 7.35pt 35.3pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">&bull;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Language Skills (Fluent in English and Swahili). </span></p>
<p class="MsoNormal" style="text-indent: -18.05pt; line-height: normal; mso-list: l0 level1 lfo2; margin: 0cm -.75pt 7.35pt 35.3pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">&bull;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Legal drafting skills with ability to prepare various legal documents. </span></p>
<p class="MsoNormal" style="text-indent: -18.05pt; line-height: normal; mso-list: l0 level1 lfo2; margin: 0cm -.75pt 7.35pt 35.3pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">&bull;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Ability to persuade, collaborate and negotiate effectively with a diverse array of people. </span></p>
<p class="MsoNormal" style="text-indent: -18.05pt; line-height: 145%; mso-list: l0 level1 lfo2; margin: 0cm -.75pt 7.35pt 35.3pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 145%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">&bull;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 145%; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Vast experience in drafting and reviewing legal documents, including contracts, pleadings and other documents. </span></p>
<p class="MsoNormal" style="text-indent: -18.05pt; line-height: normal; mso-list: l0 level1 lfo2; margin: 0cm -.75pt 7.35pt 35.3pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">&bull;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Admirable negotiating, interviewing, counseling and investigation skills; <strong style="mso-bidi-font-weight: normal;"><span style="mso-spacerun: yes;">&nbsp;</span></strong></span></p>
<p class="MsoNormal" style="line-height: normal;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';"><span style="mso-spacerun: yes;">&nbsp;</span></span></strong></p>
<h2>HOBBIES</h2>
<p class="MsoNormal" style="text-indent: -21.15pt; line-height: normal; mso-list: l1 level1 lfo3; margin: 0cm -.75pt 7.35pt 38.4pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">&bull;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Reading Books, <strong style="mso-bidi-font-weight: normal;"><span style="mso-spacerun: yes;">&nbsp;</span></strong></span></p>
<p class="MsoNormal" style="text-indent: -21.15pt; line-height: normal; mso-list: l1 level1 lfo3; margin: 0cm -.75pt 7.35pt 38.4pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">&bull;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Spots activities,<strong style="mso-bidi-font-weight: normal;"> </strong></span></p>
<p class="MsoNormal" style="text-indent: -21.15pt; line-height: normal; mso-list: l1 level1 lfo3; margin: 0cm -.75pt 7.35pt 38.4pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">&bull;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Language <strong style="mso-bidi-font-weight: normal;"><span style="mso-spacerun: yes;">&nbsp;</span></strong></span></p>
<p class="MsoNormal" style="text-indent: -21.15pt; line-height: normal; mso-list: l1 level1 lfo3; margin: 0cm -.75pt 7.35pt 38.4pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">&bull;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">Traveling, <strong style="mso-bidi-font-weight: normal;"><span style="mso-spacerun: yes;">&nbsp;</span></strong></span></p>
<p class="MsoNormal" style="margin-bottom: 6.75pt; line-height: normal;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';"><span style="mso-spacerun: yes;">&nbsp;</span></span></strong></p>
<h1 style="margin-bottom: 18.5pt;">REFEREES:<span style="font-weight: normal; text-decoration: none; text-underline: none;"> </span></h1>
<p class="MsoNormal" style="text-indent: -.5pt; line-height: normal; margin: 0cm -.75pt 7.35pt 36.55pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">1<strong style="mso-bidi-font-weight: normal;">.<span style="mso-spacerun: yes;">&nbsp;&nbsp; </span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></strong>CHARLES GOTARA </span></p>
<p class="MsoNormal" style="text-indent: -.5pt; line-height: normal; margin: 0cm -.75pt 7.35pt 36.55pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';"><span style="mso-spacerun: yes;">&nbsp;</span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>ASSISTANT REGIONAL MANAGER, </span></p>
<p class="MsoNormal" style="text-indent: -.5pt; line-height: normal; margin: 0cm -.75pt 7.35pt 36.55pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';"><span style="mso-spacerun: yes;">&nbsp;</span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>NSSF</span></p>
<p class="MsoNormal" style="text-indent: -.5pt; line-height: normal; margin: 0cm -.75pt 7.35pt 36.55pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';"><span style="mso-spacerun: yes;">&nbsp;</span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Tel: +255 (0) 757 24749 </span></p>
<p class="MsoNormal" style="margin-bottom: 6.75pt; line-height: normal;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';"><span style="mso-spacerun: yes;">&nbsp;</span></span></strong></p>
<p class="MsoNormal" style="text-indent: -.5pt; line-height: normal; margin: 0cm -.75pt 7.35pt 36.55pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';">2. <span style="mso-spacerun: yes;">&nbsp;&nbsp;</span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>SUNDAY MWENENGANGA </span></p>
<p class="MsoNormal" style="text-indent: -.5pt; line-height: normal; margin: 0cm -.75pt 7.35pt 36.55pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';"><span style="mso-spacerun: yes;">&nbsp;</span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>TANZANIA REVENUE AUTHORITY, </span></p>
<p class="MsoNormal" style="text-indent: -.5pt; line-height: normal; margin: 0cm -.75pt 7.35pt 36.55pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';"><span style="mso-spacerun: yes;">&nbsp;</span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>TAX OFFICER </span></p>
<p class="MsoNormal" style="text-indent: -.5pt; line-height: normal; margin: 0cm -.75pt 7.35pt 36.55pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';"><span style="mso-spacerun: yes;">&nbsp;</span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>MOROGORO </span><span style="mso-spacerun: yes;">&nbsp;</span></p>
<p class="MsoNormal" style="text-indent: -.5pt; line-height: normal; margin: 0cm -.75pt 7.35pt 36.55pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';"><span style="mso-spacerun: yes;">&nbsp;</span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Tel: +255 (0) 756 410 666 </span></p>
<p class="MsoNormal" style="line-height: normal; margin: 0cm 0cm 1.95pt 36.05pt;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman';"><span style="mso-spacerun: yes;">&nbsp;</span></span></p>`;